% Core triggers
coreTriggerNames = {...
    'fixation', ...
    'item_start', ...
    'item_end', ...
    'quiz_start', ...
    'quiz_end', ...
    'correct', ...
    'incorrect'
};

% Wiki triggers
wikiNames = { ...
    'actor', ...
    'bagpipe', ...
    'bellhop', ...
    'crochet', ...
    'flirt', ...
    'limousine', ...
    'ophthalmologist', ...
    'paint', ...
    'paralegal', ...
    'pub', ...
    'read', ...
    'retiree', ...
    'sail', ...
    'salamander', ...
    'treadmill' ...
};
wikiName2ID = containers.Map(wikiNames, 1:numel(wikiNames));
wikiID2Name = containers.Map(1:numel(wikiNames), wikiNames);

% 4-sent triggers
fourSentNames = {};
for item=1:150
    fourSentNames{item} = sprintf('4sent_%d', item);
end
fourSentName2ID = containers.Map(fourSentNames, 1:numel(fourSentNames));
fourSentID2Name = containers.Map(1:numel(fourSentNames), fourSentNames);

% All triggers
triggerNames = [coreTriggerNames, wikiNames, fourSentNames];
triggerName2ID = containers.Map(triggerNames, 1:numel(triggerNames));
triggerID2Name = containers.Map(1:numel(triggerNames), triggerNames);
